### ISSUE TITLE
Flink CEP 1.3.2 porting

### ISSUE THREAD

**Issue by dfsklar** [bytefish/FlinkExperiments#2]
FYI:  I'm pretty close to completing the port to flink 1.3.2, which is not backward compatible with re: to pattern selection.

I'll submit a PR when ready, but of course please let me know if you've already doing this port and are not interested in this contribution.

**Comment by bytefish** [comment]
That sounds great! 🙌 No, I am not working on it at the moment. I will happy to merge the Pull Request.

**Comment by bytefish** [comment]
It's ported. Thanks for your efforts!
