### ISSUE TITLE
Error while inserting duplicate records|(key already exists)

### ISSUE THREAD

**Issue by rajancherma** [bytefish/FlinkExperiments#4]
Is there any way to enable insert/update functionality.While inserting the duplicate record getting key duplicate error(key already exists).Can anyone please help me with this.In our case have tio update the existing the row with the new data if any.

**Comment by bytefish** [comment]
The Postgresql Sink Function I wrote only does Bulk Inserts. If you need more advanced functionality, you have to write a Sink Function, that does the upserts for you.
