### ISSUE TITLE
Error in compiling csv.mapping.LocalWeatherDataMapper

### ISSUE THREAD

**Issue by seaward** [bytefish/FlinkExperiments#6]
The method mapProperty(int, Type, BiConsumer<LocalWeatherData,TProperty>, ITypeConverter<TProperty>) in the type CsvMapping<LocalWeatherData> is not applicable for the arguments (int, Class<Float>, LocalWeatherData::setDryBulbCelsius, new IgnoreMissingValuesConverter<>(new FloatConverter(), "M"))

**Comment by bytefish** [comment]
That's not a bug actually. The code is valid Java 1.8 code, but I guess some IDEs have problems with it and highlight it as a fault. IntelliJ will happily parse this Java statement and infer the types. I guess you are using Eclipse? Anyway... Thanks for the fix, so it compiles fine for all IDEs.
