### ISSUE TITLE
Connection pool tuning

### ISSUE THREAD

**Issue by rajancherma** [bytefish/FlinkExperiments#9]
I am initializing a connection pool with size of 10 and having datastream which will insert millions of rows against the postgres table. For inserting 5 millions of rows it is taking around 8 hours when debugging in pg_stats table observed only 1 connection is active and remaining 9 connections are idle. What is the ideal configuration in order to effectively use all the connections .can you please guide me with this.

**Comment by bytefish** [comment]
Sorry, this code was written some years ago so I don't know what internals in Apache Flink might have changed. 5 million rows shouldn't take 8 hours, if you are using my implementation with an appropriate Batch size. Couldn't you write a small application, that inserts the data you want to write to see where the problem might be located?
